language: generic

services:
  - docker

before_install:
  - docker build -t dap_testing -f Dockerfile.testing .

script:
  - docker build -t dap_testing -f Dockerfile.testing .
  - docker run --rm --name dap_testing -it -e DAP_EXECUTABLE=dap dap_testing /bin/bash -l -c "rvm use 2.7.6 && gem build dap && gem install dap*.gem && bundle exec rspec spec && find /opt/bats_testing -name \*.bats | grep -v test/test_helper/ | xargs -n1 bats"
